feat: Automate version management and update Tauri application configuration
- Updated version numbers in package.json, package-lock.json, Cargo.toml, and Cargo.lock to 0.2.1.
- Added GitHub Actions workflow for publishing automatic releases.
- Extracted version number from the branch name and updated the application's version accordingly.
- Introduced script to update the Tauri version in the Cargo.toml file.
- Configured automatic commits and pushes of version changes back to the repository.
- Removed hardcoded version in tauri.conf.json to allow automatic versioning.

diff --git a/.github/workflows/publish-to-auto-release.yml b/.github/workflows/publish-to-auto-release.yml
--- a/.github/workflows/publish-to-auto-release.yml
+++ b/.github/workflows/publish-to-auto-release.yml
@@ -50,6 +50,40 @@ jobs:
 
       - name: install frontend dependencies
         run: npm install # change this to npm, pnpm or bun depending on which one you use.
+      
+      - uses: tauri-apps/tauri-action@v0
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          args: ${{ matrix.args }}
+
+      - name: Extract version from branch name
+        id: extract_version
+        run: |
+          VERSION=${GITHUB_REF#refs/heads/release/}
+          if [[ -z "$VERSION" ]]; then
+            echo "Error: Version could not be extracted from the branch name."
+            exit 1
+          fi
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+  
+      - name: Update version number
+        run: ./script/update_version $VERSION
+
+      - name: Set up Git
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+
+      - name: Commit changes
+        run: |
+          git add .
+          git commit -m "Automated commit from GitHub Actions"
+
+      - name: Push changes
+        uses: ad-m/github-push-action@v0.8.0
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
       - uses: tauri-apps/tauri-action@v0
         env:
